export const ACT_GET_ALL_SHOP = 'ACT_GET_ALL_SHOP';
export const ACT_GET_TOTAL_SHOP = 'ACT_GET_TOTAL_SHOP';
export const ACT_GET_SHOP_BY_NAME = 'ACT_GET_SHOP_BY_NAME';
export const ACT_GET_CATEGORY_NAME = 'ACT_GET_CATEGORY_NAME';
export const ADD_NEW_SHOP = 'ADD_NEW_SHOP';
export const ACT_GET_CURRENT_SHOP = 'ACT_GET_CURRENT_SHOP';
export const ACT_GET_LOGIN = 'ACT_GET_LOGIN';
export const ACT_GET_LOGOUT = 'ACT_GET_LOGOUT';
