export const ACT_GET_ALL_PRODUCT = 'ACT_GET_ALL_PRODUCT';
export const ACT_GET_TOTAL_PRODUCT = 'ACT_GET_TOTAL_PRODUCT';
export const ACT_GET_PRODUCT_BY_NAME = 'ACT_GET_PRODUCT_BY_NAME';
export const ACT_GET_CATEGORY_NAME = 'ACT_GET_CATEGORY_NAME';
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
