export const ACT_GET_ALL_BANNER = 'ACT_GET_ALL_BANNER';
export const ADD_NEW_BANNER = 'ADD_NEW_BANNER';
export const ACT_GET_TOTAL_BANNER = 'ACT_GET_TOTAL_BANNER';
export const ACT_GET_BANNER_BY_NAME = 'ACT_GET_BANNER_BY_NAME';
export const ACT_GET_CURRENT_BANNER = 'ACT_GET_CURRENT_BANNER';
