export const ACT_GET_ALL_ORDER = 'ACT_GET_ALL_ORDER';
export const ACT_GET_TOTAL_ORDER = 'ACT_GET_TOTAL_ORDER';
export const ACT_GET_ORDER_BY_NAME = 'ACT_GET_ORDER_BY_NAME';
export const ACT_GET_CATEGORY_NAME = 'ACT_GET_CATEGORY_NAME';
export const ADD_NEW_ORDER = 'ADD_NEW_ORDER';
export const ACT_GET_CURRENT_ORDER = 'ACT_GET_CURRENT_ORDER';
