export const ACT_GET_ALL_USER = 'ACT_GET_ALL_USER';
export const ACT_GET_TOTAL_USER = 'ACT_GET_TOTAL_USER';
export const ACT_GET_USER_BY_NAME = 'ACT_GET_USER_BY_NAME';
export const ACT_GET_CATEGORY_NAME = 'ACT_GET_CATEGORY_NAME';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const ACT_GET_CURRENT_USER = 'ACT_GET_CURRENT_USER';
export const ACT_GET_LOGIN = 'ACT_GET_LOGIN';
export const ACT_GET_LOGOUT = 'ACT_GET_LOGOUT';
